// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMK7uC9A-y_fnuBpRgkNfaPMtx2FAuqdE',
    appId: '1:10173639665:web:c8ce7f387bef4cfe5bf250',
    messagingSenderId: '10173639665',
    projectId: 'momen-todo-depi-22664',
    authDomain: 'momen-todo-depi-22664.firebaseapp.com',
    storageBucket: 'momen-todo-depi-22664.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcOYZQm3FHEQ7r1ttn3L4f70XHr27mJ4',
    appId: '1:10173639665:android:5643f7b9bea008e15bf250',
    messagingSenderId: '10173639665',
    projectId: 'momen-todo-depi-22664',
    storageBucket: 'momen-todo-depi-22664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMK7uC9A-y_fnuBpRgkNfaPMtx2FAuqdE',
    appId: '1:10173639665:ios:e7792010b30272695bf250',
    messagingSenderId: '10173639665',
    projectId: 'momen-todo-depi-22664',
    storageBucket: 'momen-todo-depi-22664.appspot.com',
    iosBundleId: 'com.example.momensalman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMK7uC9A-y_fnuBpRgkNfaPMtx2FAuqdE',
    appId: '1:10173639665:ios:e7792010b30272695bf250',
    messagingSenderId: '10173639665',
    projectId: 'momen-todo-depi-22664',
    storageBucket: 'momen-todo-depi-22664.appspot.com',
    iosBundleId: 'com.example.momensalman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMK7uC9A-y_fnuBpRgkNfaPMtx2FAuqdE',
    appId: '1:10173639665:web:b8391b44e313c1985bf250',
    messagingSenderId: '10173639665',
    projectId: 'momen-todo-depi-22664',
    storageBucket: 'momen-todo-depi-22664.appspot.com',
  );
}
