name: momensalman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  http: ^1.6.0
  sqflite: ^2.4.2
  shared_preferences: ^2.2.2
  path: ^1.9.0
  
  # Firebase Dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  firebase_ui_auth: ^1.13.0
  google_sign_in: ^6.3.0
  
  # Firebase Cloud Messaging
  firebase_messaging: ^14.7.10
  
  # Local Notifications
  flutter_local_notifications: ^17.2.2
  
  # Web compatibility
  js: ^0.7.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile1.png
    - assets/images/post.jpg
